name: Weave Back
on:
  schedule:
    - cron: '0 0/1 * * *'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 langchain langchain_google_genai langchain_openai python-dotenv tiktoken selenium-stealth pydantic serpapi libsql_experimental
      
      - name: Install Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      - name: Run Python script
        env:
          PERPLEXITY_API: ${{ secrets.PERPLEXITY_API }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
        run: python cronjob.py
